name: Leaderboard

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  # Build
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup image
      uses: ./.github/workflows/setup.yml
      with:
        python-version: "3.10"
        nim-version: "2.0.0"
        clang-version: "16"
        deno-version: "v1.x"
        zig-version: "0.12.0"

    - name: Setup netlify
      run: npm install -g netlify-cli

    - name: Build
      run: ./leaderboard.sh
      continue-on-error: true
      env:
        NETLIFY_AUTH: ${{ secrets.NETLIFY_AUTH }}
