name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      days:
        description: Run specific days (space delimiter)
        required: true

env:
  INPUTS_DAYS: ${{ github.event.inputs.days }}

jobs:
  build:
    uses: ./.github/workflows/setup.yml
    with:
      - python-version: "3.10"
      - nim-version: "2.0.0"
      - clang-version: "16"
      - deno-version: "v1.x"
      - zig-version: "0.12.0"

    # Build
    build-steps:
      runs-on: ubuntu-22.04
      needs: build

      steps:
        - name: Build
          run: ./build.sh
